# Generated by Django 3.1.4 on 2021-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210104_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipe.ShoppingCart'),
        ),
    ]
