# Generated by Django 3.1.4 on 2021-01-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20210104_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='badge_color',
            field=models.CharField(choices=[('orange', 'orange'), ('green', 'green'), ('purple', 'purple')], default='orange', max_length=32),
        ),
    ]
