# Generated by Django 3.1.4 on 2021-01-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210107_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
