# Generated by Django 3.1.4 on 2021-01-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_auto_20210112_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
